### ISSUE TITLE
ImportError: No module named decouple

### ISSUE THREAD

**Issue by znwright** [app-generator/flask-dashboard-atlantis-dark#3] opened 2020-12-21 13:50 UTC
Tried downloading on a mac per the instructions. When I tried to open in browser, got this message: ImportError: No module named decouple. I tried changing to python-decouple==3.1 in the requirements.txt file but did not commit changes.

**Comment by app-generator** [comment] 2020-12-21 19:12
Hello, 

Thank you for using our products. Just tested on CentOS 7, Ubuntu 18 LTS and Windows 10. 
We cannot reproduce the issue: 

CentOS compilation log:

```bash
flask-dashboard-atlantis-dark]$ virtualenv env
flask-dashboard-atlantis-dark]$ source env/bin/activate
flask-dashboard-atlantis-dark]$ pip3 install -r requirements.txt
Collecting flask
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
...
Installing collected packages: MarkupSafe, Jinja2, Werkzeug, itsdangerous, click, flask, flask-login, SQLAlchemy, flask-sqlalchemy, python-editor, Mako, six, python-dateutil, alembic, flask-migrate, WTForms, flask-wtf, dnspython, idna, email-validator, python-decouple, gunicorn
Successfully installed Jinja2-2.11.2 Mako-1.1.3 MarkupSafe-1.1.1 SQLAlchemy-1.3.22 WTForms-2.3.3 Werkzeug-1.0.1 alembic-1.4.3 click-7.1.2 dnspython-2.0.0 email-validator-1.1.2 flask-1.1.2 flask-login-0.5.0 flask-migrate-2.5.3 flask-sqlalchemy-2.4.4 flask-wtf-0.14.3 gunicorn-20.0.4 idna-2.10 itsdangerous-1.1.0 python-dateutil-2.8.1 python-decouple-3.3 python-editor-1.0.4 six-1.15.0
...
```

The concerned package is listed under version 3.3 `python-decouple-3.3`
The build log on CentOS and Windows is similar. 

Looks like an environmental issue. To move forward try this set up:

1 - deactivate the virtual environment (if still active)
2 - install `python-decouple-3.3` using pip (Python2) as global dependency
3 - install `python-decouple-3.3` using pip3 (Python3) as global dependency
4 - follow the steps provided in the README 

The app should start. 
We keep this issue opened. Let us know your progress.

**Comment by znwright** [comment] 2020-12-22 01:51
That worked like a charm. Once I followed your recommendations, it threw similar errors for flask_migrate and flask_wtf but the same process worked. So if someone else has this issue, we know how to fix it. Make sure the requirements are installed for pipPython 2 as well. Thanks so much. -Zach

**Comment by app-generator** [comment] 2020-12-22 05:36
Hello, 

The app is built for Python3 and the interactions with Python2 and global packages installation is basically a workaround. 
Try to read more about the virtual environment and how to manage it properly on a Mac OS. 

P.S. Thank you for using our products.
I will close this issue.

**Closed by app-generator** 2020-12-22 05:36 UTC

**Comment by znwright** [comment] 2020-12-22 13:34
I see. Alright I will keep learning, thanks!
